name: CI Pipeline - coderider

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    name: ejecute pruebas
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - name: checkout del codigo
        uses: actions/checkout@v4

      - name: configurar Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: instalar dependencias
        run: npm install

      - name: Ejecutar pruebas
        run: npm test

      - name: verificar sintaxis del codigo
        run: node --check src/app.js